name: "Джон Доу"
picture: "assets/img/picture.jpg"
bio: "Джон Доу, CEO Flex.ru"
meta:
  lang: "ru"
  description: "Джон Доу, CEO Flex.ru"
  title: "Джон Доу"
  author: "Джон Доу"
  siteUrl: "https://noverd.github.io/python_taplink/"
links:
  - name: "Github"
    url: "https://github.com/noverd"
  - name: "Dev.to"
    url: "https://dev.to/42"
  - name: "Telegram"
    url: "https://t.me/42"
  - name: "Instagram"
    url: "https://www.instagram.com/42"
theme: "custom"
